# mockery v3.4.0
all: true
log-level: info

packages:
  github.com/Neimess/zorkin-store-project/internal/service/attribute:
    config:
      filename: attribute_service_mock.go
      dir: '{{.InterfaceDir}}/mocks'
      structname: MockAttributeRepository
      pkgname: mocks
      formatter: goimports
      template: testify

  github.com/Neimess/zorkin-store-project/internal/service/category:
    config:
      filename: category_service_mock.go
      dir: '{{.InterfaceDir}}/mocks'
      structname: MockCategoryRepository
      pkgname: mocks
      formatter: goimports
      template: testify

  github.com/Neimess/zorkin-store-project/internal/service/preset:
    config:
      filename: preset_service_mock.go
      dir: '{{.InterfaceDir}}/mocks'
      structname: MockPresetRepository
      pkgname: mocks
      formatter: goimports
      template: testify

  github.com/Neimess/zorkin-store-project/internal/service/product:
    config:
      filename: product_service_mock.go
      dir: '{{.InterfaceDir}}/mocks'
      structname: MockProductRepository
      pkgname: mocks
      formatter: goimports
      template: testify

  github.com/Neimess/zorkin-store-project/internal/transport/http/restHTTP/product:
    config:
      filename: product_handler_mock.go
      dir: '{{.InterfaceDir}}/mocks'
      structname: MockProductService
      pkgname: mocks
      formatter: goimports
      template: testify

  github.com/Neimess/zorkin-store-project/internal/transport/http/restHTTP/category:
    config:
      filename: category_handler_mock.go
      dir: '{{.InterfaceDir}}/mocks'
      structname: MockCategoryService
      pkgname: mocks
      formatter: goimports
      template: testify

  github.com/Neimess/zorkin-store-project/internal/transport/http/restHTTP/preset:
    config:
      filename: preset_handler_mock.go
      dir: '{{.InterfaceDir}}/mocks'
      structname: MockPresetService
      pkgname: mocks
      formatter: goimports
      template: testify

  github.com/Neimess/zorkin-store-project/internal/transport/http/restHTTP/attribute:
    config:
      filename: attribute_handler_mock.go
      dir: '{{.InterfaceDir}}/mocks'
      structname: MockAttributeService
      pkgname: mocks
      formatter: goimports
      template: testify
