// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7cab1c76DecodeGithubComNeimessZorkinStoreProjectInternalDomain(in *jlexer.Lexer, out *Attribute) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "attribute_id":
			out.ID = int64(in.Int64())
		case "name":
			out.Name = string(in.String())
		case "slug":
			out.Slug = string(in.String())
		case "data_type":
			out.DataType = AttrDataType(in.String())
		case "unit":
			out.Unit = string(in.String())
		case "is_filterable":
			out.IsFilterable = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7cab1c76EncodeGithubComNeimessZorkinStoreProjectInternalDomain(out *jwriter.Writer, in Attribute) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"attribute_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"slug\":"
		out.RawString(prefix)
		out.String(string(in.Slug))
	}
	{
		const prefix string = ",\"data_type\":"
		out.RawString(prefix)
		out.String(string(in.DataType))
	}
	if in.Unit != "" {
		const prefix string = ",\"unit\":"
		out.RawString(prefix)
		out.String(string(in.Unit))
	}
	{
		const prefix string = ",\"is_filterable\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsFilterable))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Attribute) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7cab1c76EncodeGithubComNeimessZorkinStoreProjectInternalDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Attribute) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7cab1c76EncodeGithubComNeimessZorkinStoreProjectInternalDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Attribute) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7cab1c76DecodeGithubComNeimessZorkinStoreProjectInternalDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Attribute) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7cab1c76DecodeGithubComNeimessZorkinStoreProjectInternalDomain(l, v)
}
