// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6a91a67cDecodeGithubComNeimessZorkinStoreProjectInternalDomain(in *jlexer.Lexer, out *CategoryAttributePriority) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "category_id":
			out.CategoryID = int64(in.Int64())
		case "attribute_id":
			out.AttributeID = int64(in.Int64())
		case "priority":
			out.Priority = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a91a67cEncodeGithubComNeimessZorkinStoreProjectInternalDomain(out *jwriter.Writer, in CategoryAttributePriority) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.CategoryID))
	}
	{
		const prefix string = ",\"attribute_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.AttributeID))
	}
	{
		const prefix string = ",\"priority\":"
		out.RawString(prefix)
		out.Int(int(in.Priority))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CategoryAttributePriority) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a91a67cEncodeGithubComNeimessZorkinStoreProjectInternalDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CategoryAttributePriority) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a91a67cEncodeGithubComNeimessZorkinStoreProjectInternalDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CategoryAttributePriority) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a91a67cDecodeGithubComNeimessZorkinStoreProjectInternalDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CategoryAttributePriority) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a91a67cDecodeGithubComNeimessZorkinStoreProjectInternalDomain(l, v)
}
func easyjson6a91a67cDecodeGithubComNeimessZorkinStoreProjectInternalDomain1(in *jlexer.Lexer, out *CategoryAttribute) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "category_id":
			out.CategoryID = int64(in.Int64())
		case "attribute_id":
			out.AttributeID = int64(in.Int64())
		case "is_required":
			out.IsRequired = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a91a67cEncodeGithubComNeimessZorkinStoreProjectInternalDomain1(out *jwriter.Writer, in CategoryAttribute) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.CategoryID))
	}
	{
		const prefix string = ",\"attribute_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.AttributeID))
	}
	{
		const prefix string = ",\"is_required\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsRequired))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CategoryAttribute) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a91a67cEncodeGithubComNeimessZorkinStoreProjectInternalDomain1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CategoryAttribute) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a91a67cEncodeGithubComNeimessZorkinStoreProjectInternalDomain1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CategoryAttribute) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a91a67cDecodeGithubComNeimessZorkinStoreProjectInternalDomain1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CategoryAttribute) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a91a67cDecodeGithubComNeimessZorkinStoreProjectInternalDomain1(l, v)
}
func easyjson6a91a67cDecodeGithubComNeimessZorkinStoreProjectInternalDomain2(in *jlexer.Lexer, out *Category) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a91a67cEncodeGithubComNeimessZorkinStoreProjectInternalDomain2(out *jwriter.Writer, in Category) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Category) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a91a67cEncodeGithubComNeimessZorkinStoreProjectInternalDomain2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Category) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a91a67cEncodeGithubComNeimessZorkinStoreProjectInternalDomain2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Category) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a91a67cDecodeGithubComNeimessZorkinStoreProjectInternalDomain2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Category) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a91a67cDecodeGithubComNeimessZorkinStoreProjectInternalDomain2(l, v)
}
