// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/product": {
            "post": {
                "description": "Creates a new product and returns its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create product",
                "parameters": [
                    {
                        "description": "Product to create",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns created product ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/product/detailed": {
            "post": {
                "description": "Creates a new product with its attributes and returns the created ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create product with attributes",
                "parameters": [
                    {
                        "description": "Product to create",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns created product ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/product/{id}": {
            "get": {
                "description": "Returns a product with its attributes by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns product details",
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "invalid request payload"
                }
            }
        },
        "github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueRequest": {
            "type": "object",
            "required": [
                "attribute_id",
                "value"
            ],
            "properties": {
                "attribute_id": {
                    "type": "integer",
                    "example": 2
                },
                "value": {
                    "type": "string",
                    "example": "1.25"
                }
            }
        },
        "github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueResponse": {
            "type": "object",
            "properties": {
                "attribute_id": {
                    "type": "integer",
                    "example": 2
                },
                "is_filterable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "example": "Объём"
                },
                "slug": {
                    "type": "string",
                    "example": "volume"
                },
                "unit": {
                    "type": "string",
                    "example": "л"
                },
                "value": {
                    "type": "string",
                    "example": "1.25"
                }
            }
        },
        "github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductCreateRequest": {
            "type": "object",
            "required": [
                "category_id",
                "name",
                "price"
            ],
            "properties": {
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueRequest"
                    }
                },
                "category_id": {
                    "type": "integer",
                    "example": 1
                },
                "description": {
                    "type": "string",
                    "example": "Прочный плиточный материал"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/image.png"
                },
                "name": {
                    "type": "string",
                    "minLength": 2,
                    "example": "Керамогранит"
                },
                "price": {
                    "type": "number",
                    "example": 3490
                }
            }
        },
        "github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductIDResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 42
                },
                "message": {
                    "type": "string",
                    "example": "Product created successfully"
                }
            }
        },
        "github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductResponse": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueResponse"
                    }
                },
                "category_id": {
                    "type": "integer",
                    "example": 1
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-06-20T15:00:00Z"
                },
                "description": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "Керамогранит"
                },
                "price": {
                    "type": "number",
                    "example": 3490
                },
                "product_id": {
                    "type": "integer",
                    "example": 10
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "Zorkin Store API",
	Description:      "API for managing products and categories",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
