definitions:
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse:
    properties:
      message:
        example: invalid request payload
        type: string
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueRequest:
    properties:
      attribute_id:
        example: 2
        type: integer
      value:
        example: "1.25"
        type: string
    required:
    - attribute_id
    - value
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueResponse:
    properties:
      attribute_id:
        example: 2
        type: integer
      is_filterable:
        type: boolean
      name:
        example: Объём
        type: string
      slug:
        example: volume
        type: string
      unit:
        example: л
        type: string
      value:
        example: "1.25"
        type: string
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductCreateRequest:
    properties:
      attributes:
        items:
          $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueRequest'
        type: array
      category_id:
        example: 1
        type: integer
      description:
        example: Прочный плиточный материал
        type: string
      image_url:
        example: https://example.com/image.png
        type: string
      name:
        example: Керамогранит
        minLength: 2
        type: string
      price:
        example: 3490
        type: number
    required:
    - category_id
    - name
    - price
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductIDResponse:
    properties:
      id:
        example: 42
        type: integer
      message:
        example: Product created successfully
        type: string
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductResponse:
    properties:
      attributes:
        items:
          $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueResponse'
        type: array
      category_id:
        example: 1
        type: integer
      created_at:
        example: "2025-06-20T15:00:00Z"
        type: string
      description:
        type: string
      image_url:
        type: string
      name:
        example: Керамогранит
        type: string
      price:
        example: 3490
        type: number
      product_id:
        example: 10
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for managing products and categories
  title: Zorkin Store API
  version: "1.0"
paths:
  /api/product:
    post:
      consumes:
      - application/json
      description: Creates a new product and returns its ID
      parameters:
      - description: Product to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Returns created product ID
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductIDResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: Create product
      tags:
      - products
  /api/product/{id}:
    get:
      consumes:
      - application/json
      description: Returns a product with its attributes by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Returns product details
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductResponse'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: Get product
      tags:
      - products
  /api/product/detailed:
    post:
      consumes:
      - application/json
      description: Creates a new product with its attributes and returns the created
        ID.
      parameters:
      - description: Product to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Returns created product ID
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductIDResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: Create product with attributes
      tags:
      - products
schemes:
- http
swagger: "2.0"
