definitions:
  github_com_Neimess_zorkin-store-project_internal_transport_dto.CategoryCreateRequest:
    properties:
      name:
        example: Плитка
        minLength: 2
        type: string
    required:
    - name
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.CategoryResponse:
    properties:
      id:
        example: 3
        type: integer
      name:
        example: Керамогранит
        type: string
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.CategoryUpdateRequest:
    properties:
      name:
        example: Керамогранит
        minLength: 2
        type: string
    required:
    - name
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse:
    properties:
      message:
        example: invalid request payload
        type: string
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.IDResponse:
    properties:
      id:
        example: 42
        type: integer
      message:
        example: created
        type: string
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueRequest:
    properties:
      attribute_id:
        example: 2
        type: integer
      value:
        example: "1.25"
        type: string
    required:
    - attribute_id
    - value
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueResponse:
    properties:
      attribute_id:
        example: 2
        type: integer
      is_filterable:
        type: boolean
      name:
        example: Объём
        type: string
      slug:
        example: volume
        type: string
      unit:
        example: л
        type: string
      value:
        example: "1.25"
        type: string
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductCreateRequest:
    properties:
      attributes:
        items:
          $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueRequest'
        type: array
      category_id:
        example: 1
        type: integer
      description:
        example: Прочный плиточный материал
        type: string
      image_url:
        example: https://example.com/image.png
        type: string
      name:
        example: Керамогранит
        minLength: 2
        type: string
      price:
        example: 3490
        type: number
    required:
    - category_id
    - name
    - price
    type: object
  github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductResponse:
    properties:
      attributes:
        items:
          $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductAttributeValueResponse'
        type: array
      category_id:
        example: 1
        type: integer
      created_at:
        example: "2025-06-20T15:00:00Z"
        type: string
      description:
        type: string
      image_url:
        type: string
      name:
        example: Керамогранит
        type: string
      price:
        example: 3490
        type: number
      product_id:
        example: 10
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for managing products and categories
  title: Zorkin Store API
  version: "1.0"
paths:
  /api/category:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.CategoryResponse'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: List categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      parameters:
      - description: Category to create
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.CategoryCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: Create category
      tags:
      - categories
  /api/category/{id}:
    delete:
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: Delete category
      tags:
      - categories
    get:
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.CategoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: Get category by ID
      tags:
      - categories
    put:
      consumes:
      - application/json
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: New name
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.CategoryUpdateRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: Update category
      tags:
      - categories
  /api/product:
    post:
      consumes:
      - application/json
      description: Creates a new product and returns its ID
      parameters:
      - description: Product to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Returns created product ID
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.IDResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: Create product
      tags:
      - products
  /api/product/{id}:
    get:
      consumes:
      - application/json
      description: Returns a product with its attributes by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Returns product details
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductResponse'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: Get product
      tags:
      - products
  /api/product/detailed:
    post:
      consumes:
      - application/json
      description: Creates a new product with its attributes and returns the created
        ID.
      parameters:
      - description: Product to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ProductCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Returns created product ID
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.IDResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Neimess_zorkin-store-project_internal_transport_dto.ErrorResponse'
      summary: Create product with attributes
      tags:
      - products
schemes:
- http
swagger: "2.0"
