// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Neimess/zorkin-store-project/internal/domain/preset"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPresetRepository creates a new instance of MockPresetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPresetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPresetRepository {
	mock := &MockPresetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPresetRepository is an autogenerated mock type for the PresetRepository type
type MockPresetRepository struct {
	mock.Mock
}

type MockPresetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPresetRepository) EXPECT() *MockPresetRepository_Expecter {
	return &MockPresetRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPresetRepository
func (_mock *MockPresetRepository) Create(ctx context.Context, p *preset.Preset) (int64, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *preset.Preset) (int64, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *preset.Preset) int64); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *preset.Preset) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPresetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *preset.Preset
func (_e *MockPresetRepository_Expecter) Create(ctx interface{}, p interface{}) *MockPresetRepository_Create_Call {
	return &MockPresetRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockPresetRepository_Create_Call) Run(run func(ctx context.Context, p *preset.Preset)) *MockPresetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *preset.Preset
		if args[1] != nil {
			arg1 = args[1].(*preset.Preset)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresetRepository_Create_Call) Return(n int64, err error) *MockPresetRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPresetRepository_Create_Call) RunAndReturn(run func(ctx context.Context, p *preset.Preset) (int64, error)) *MockPresetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockPresetRepository
func (_mock *MockPresetRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPresetRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPresetRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPresetRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockPresetRepository_Delete_Call {
	return &MockPresetRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPresetRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockPresetRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresetRepository_Delete_Call) Return(err error) *MockPresetRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPresetRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockPresetRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockPresetRepository
func (_mock *MockPresetRepository) Get(ctx context.Context, id int64) (*preset.Preset, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *preset.Preset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*preset.Preset, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *preset.Preset); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*preset.Preset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresetRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPresetRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPresetRepository_Expecter) Get(ctx interface{}, id interface{}) *MockPresetRepository_Get_Call {
	return &MockPresetRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockPresetRepository_Get_Call) Run(run func(ctx context.Context, id int64)) *MockPresetRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresetRepository_Get_Call) Return(preset1 *preset.Preset, err error) *MockPresetRepository_Get_Call {
	_c.Call.Return(preset1, err)
	return _c
}

func (_c *MockPresetRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id int64) (*preset.Preset, error)) *MockPresetRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListDetailed provides a mock function for the type MockPresetRepository
func (_mock *MockPresetRepository) ListDetailed(ctx context.Context) ([]preset.Preset, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDetailed")
	}

	var r0 []preset.Preset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]preset.Preset, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []preset.Preset); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]preset.Preset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresetRepository_ListDetailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDetailed'
type MockPresetRepository_ListDetailed_Call struct {
	*mock.Call
}

// ListDetailed is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPresetRepository_Expecter) ListDetailed(ctx interface{}) *MockPresetRepository_ListDetailed_Call {
	return &MockPresetRepository_ListDetailed_Call{Call: _e.mock.On("ListDetailed", ctx)}
}

func (_c *MockPresetRepository_ListDetailed_Call) Run(run func(ctx context.Context)) *MockPresetRepository_ListDetailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPresetRepository_ListDetailed_Call) Return(presets []preset.Preset, err error) *MockPresetRepository_ListDetailed_Call {
	_c.Call.Return(presets, err)
	return _c
}

func (_c *MockPresetRepository_ListDetailed_Call) RunAndReturn(run func(ctx context.Context) ([]preset.Preset, error)) *MockPresetRepository_ListDetailed_Call {
	_c.Call.Return(run)
	return _c
}

// ListShort provides a mock function for the type MockPresetRepository
func (_mock *MockPresetRepository) ListShort(ctx context.Context) ([]preset.Preset, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListShort")
	}

	var r0 []preset.Preset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]preset.Preset, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []preset.Preset); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]preset.Preset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresetRepository_ListShort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListShort'
type MockPresetRepository_ListShort_Call struct {
	*mock.Call
}

// ListShort is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPresetRepository_Expecter) ListShort(ctx interface{}) *MockPresetRepository_ListShort_Call {
	return &MockPresetRepository_ListShort_Call{Call: _e.mock.On("ListShort", ctx)}
}

func (_c *MockPresetRepository_ListShort_Call) Run(run func(ctx context.Context)) *MockPresetRepository_ListShort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPresetRepository_ListShort_Call) Return(presets []preset.Preset, err error) *MockPresetRepository_ListShort_Call {
	_c.Call.Return(presets, err)
	return _c
}

func (_c *MockPresetRepository_ListShort_Call) RunAndReturn(run func(ctx context.Context) ([]preset.Preset, error)) *MockPresetRepository_ListShort_Call {
	_c.Call.Return(run)
	return _c
}
