env: development

http_server:
    address: "0.0.0.0:8080"
    max_header_bytes: 1048576
    read_timeout: 10s
    write_timeout: 10s
    shutdown_timeout: 5s
    idle_timeout: 120s
    enable_cors: false
    enable_gzip: false
    enable_pprof: true
storage:
    conn_max_timeout: 30s
jwt_config:
    issuer: zorkindev.ru
    audience: admin_app
    algorithm: HS256
swagger:
    enable: true
    host: your-domain
    scheme: [https, http]
    version: 1.0.0
