env: local
admin_code: "admin123"
http_server:
    address: "0.0.0.0:8080"
    max_header_bytes: 1048576
    read_timeout: 10s
    write_timeout: 10s
    shutdown_timeout: 5s
    idle_timeout: 120s
    enable_cors: true
    enable_pprof: true
    enable_gzip: true
storage:
    host: localhost
    port: 5432
    user: devuser
    password: devpassword
    dbname: devdb
    conn_max_timeout: 30s
jwt_config:
    issuer: zorkindev.ru
    audience: admin_app
    algorithm: HS256
swagger:
    enable: true
    host: your-domain
    scheme: [https, http]
    version: 1.0.0
