env: production

http_server:
    address: "0.0.0.0:8080"
    max_header_bytes: 1048576
    read_timeout: 10s
    write_timeout: 10s
    shutdown_timeout: 5s
    idle_timeout: 120s
    enable_cors: false
    enable_pprof: false
    enable_gzip: false
storage:
    conn_max_timeout: 40s
jwt_config:
    issuer: inputIssuer
    audience: admin_app
    algorithm: HS256
swagger:
    enable: false
