env: test
version: "integration_test"
http_server:
  address: ":8080"
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 30s
  max_header_bytes: 1048576
storage:
  host: localhost
  port: 5432
  user: testuser
  password: testpassword
  dbname: testdb
  sslmode: disable
  conn_max_timeout: 1h
  max_open_conns: 10
jwt_config:
  jwt_secret: "testsecret"
  issuer: "test"
  audience: "test"
  algorithm: "HS256"
swagger:
  host: "localhost:8080"
  schemes: ["http"]
  version: "integration_test"
