name: zorkin_backend_ci
description: CI for zorkin backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

env:
  GO_VERSION: '1.24'
  MODULE_PATH: ./backend

# ──────────────────────────────────────────────────────────────────────────────
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
        
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./backend
  
      - name: Run golangci-lint
        working-directory: ./backend
        run: golangci-lint run ./...

      - name: Check gofmt
        working-directory: ./backend
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "❌ Found unformatted files:"
            echo "$UNFORMATTED"
            exit 1
          fi
        shell: bash
      
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        working-directory: ./backend
        run: staticcheck ./...

  test:
    name: Test & Vet
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules & build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - name: Download deps
        working-directory: ${{ env.MODULE_PATH }}
        run: go mod download

      - name: Vet
        working-directory: ${{ env.MODULE_PATH }}
        run: go vet ./...

      - name: Test (race + coverage)
        working-directory: ${{ env.MODULE_PATH }}
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: ${{ env.MODULE_PATH }}/coverage.out
          retention-days: 7
