name: docker-release
description: Manual release to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g. latest, v1.0.0)'
        required: true
        default: 'latest'

env:
  MODULE_PATH: ./backend
  REGISTRY: docker.io
  BACKEND_IMAGE: yourdockerhubuser/store-backend
  MIGRATE_IMAGE: yourdockerhubuser/store-migrate

jobs:
  build-and-push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
            context: ${{ env.MODULE_PATH }}
            file: ${{ env.MODULE_PATH }}/build/store-backend/Dockerfile
            push: true
            tags: ${{ env.BACKEND_IMAGE }}:${{ github.event.inputs.tag }}
    
      - name: Build & Push Migrate Image
        uses: docker/build-push-action@v5
        with:
            context: ${{ env.MODULE_PATH }}
            file: ${{ env.MODULE_PATH }}/build/store-migrate/Dockerfile
            push: true
            tags: ${{ env.MIGRATE_IMAGE }}:${{ github.event.inputs.tag }}

