name: docker-release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g. latest, v1.0.0)'
        required: true
        default: 'latest'
      version:
        description: 'Release version'
        required: true
      goos:
        description: 'Target OS (e.g. linux, windows)'
        required: true
        default: linux
      goarch:
        description: 'Target ARCH (e.g. amd64, arm64)'
        required: true
        default: amd64

env:
  MODULE_PATH: ./backend
  REGISTRY: docker.io
  BACKEND_IMAGE: neimes/store-backend
  MIGRATE_IMAGE: neimes/store-migrate

jobs:
  build-and-push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set build metadata
        id: meta
        run: |
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "build_time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.MODULE_PATH }}
          file: ${{ env.MODULE_PATH }}/build/backend/Dockerfile
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:${{ github.event.inputs.tag }}
          cache-from: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache,mode=max
          build-args: |
            VERSION=${{ github.event.inputs.version }}
            COMMIT=${{ github.sha }}
            BUILD_DATE=${{ steps.meta.outputs.build_time }}
    
      - name: Build & Push Migrate Image
        uses: docker/build-push-action@v5
        with:
            context: ${{ env.MODULE_PATH }}
            file: ${{ env.MODULE_PATH }}/build/migrate/Dockerfile
            push: true
            tags: ${{ env.MIGRATE_IMAGE }}:${{ github.event.inputs.tag }}

